### ISSUE TITLE
Bug in updatets.py Path

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD-translations#194]
Version:
  0.5

First, lets find all necessary tools on your system
Found Qt 6.4.0

......
.....
All Qt tools have been found!
 	(qmake not needed for Qt 6 and later)
 	lupdate
 	(pylupdate not needed for Qt 6 and later)
 	lconvert

==============================================

 BEGINNING TRANSLATION EXTRACTION 

WARNING - Updating Path ONLY
Traceback (most recent call last):
  File "/home/aleksandr/test_crowdin/FreeCAD/src/Tools/./updatets.py", line 259, in <module>
    main(sys.argv[1])
  File "/home/aleksandr/test_crowdin/FreeCAD/src/Tools/./updatets.py", line 248, in main
    update_translation(i)
  File "/home/aleksandr/test_crowdin/FreeCAD/src/Tools/./updatets.py", line 221, in update_translation
    f.write(p.stdout.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

@chennes can you look this?

**Comment by chennes** [comment]
I'm surprised to see a byte order marker on stdout there, but maybe if we explicitly set the encoding that will take care of it.
